services:
  frontend:
    ports:
      - "3000:5173"
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    command: ["npm", "run", "_dev"]
  test_frontend:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    ports:
      - "5173:5173"
    build:
      context: .
      target: test
    volumes:
      - .:/app
    command: ["npm", "run", "_dev"]
  tests:
    depends_on:
      test_frontend:
        condition: service_healthy
    image: mcr.microsoft.com/playwright:v1.39.0-jammy
    ipc: host # Keeps chrome from OOMing
    environment:
      BASE_URL: "http://test_frontend:5173"
      DISPLAY: "host.docker.internal:0"
    working_dir: /app # Default working dir is /
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
  tests_ui:
    depends_on:
      test_frontend:
        condition: service_healthy
    image: mcr.microsoft.com/playwright:v1.39.0-jammy
    environment:
      BASE_URL: "http://localhost:5173"
      DISPLAY: "${DISPLAY}"
    working_dir: /app # Default working dir is /
    ports:
      - "3001:3001"
    network_mode: host
    volumes:
      - ".:/app"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
