FROM node:19.1.0-bullseye
WORKDIR /app
USER root

COPY .npmrc ./
COPY package*.json ./
RUN npm install
RUN npx playwright install --with-deps
RUN npm install concurrently http-server wait-on

COPY . .

RUN npm run build-storybook --quiet
RUN npm run build

ENV BASE_URL="http://localhost:3000"

ENTRYPOINT npm run test:unit \
  && npx concurrently -k -s first -n "Storybook,App,Component Tests,Feature Tests" -c "bgGray.white,auto" \
    "npx http-server storybook-static --port 6006 --silent" \
    "npx wait-on tcp:6006 && npm run test:components" \
  && npx concurrently -k -s first -n "Storybook,App,Component Tests,Feature Tests" -c "bgGray.white,auto" \
    "npx http-server build --port 3000 --silent" \
    "npx wait-on tcp:3000 && npm run test:features"
