services:
  frontend:
    healthcheck:
      # test: ["CMD-SHELL", "wget -O- http://localhost:5173 || exit 1"]
      test: ["CMD-SHELL", "curl -f http://localhost:5173 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    ports:
      - 3000:5173
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    command: ["npm", "run", "_dev"]
  tests:
    depends_on:
      frontend:
        condition: service_healthy
    image: mcr.microsoft.com/playwright:v1.39.0-jammy
    ipc: host
    environment:
      PORT: 5173
    volumes:
      - .:/app
    command: ["npm", "run", "_test:features"]
