services:
  frontend:
    ports:
      - 3000:3000
    build:
      context: .
    working_dir: "/app"
    volumes:
      - .:/app
    command: ["npm", "run", "_dev"]
    environment:
      PORT: "3000"
