services:
  frontend:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 50s
    ports:
      - 3000:5173
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    command: ["npm", "run", "_dev"]
  tests:
    depends_on:
      frontend:
        condition: service_healthy
    build:
      context: .
      target: test
    command: ["npm", "run", "_test:features"]
    environment:
      PORT: 5173
    volumes:
      - .:/app
