services:
  frontend:
    env_file:
      - .env
    ports:
      - 3000:3000
    build:
      context: ../Dockerfile
      target: dev
    working_dir: "/app"
    volumes:
      - .:/app
    command: ["npm", "start"]
