services:
  frontend:
    environment:
      REACT_APP_API_BASE_URL: "http://api:80"
      PORT: 3000
    build:
      target: base
    expose:
      - 3000
  api:
    environment:
      PORT: 80
    expose:
      - 80
  tests:
    build:
      context: ../tests/
    environment:
      BASE_URL: "http://frontend:3000"
    depends_on:
      - frontend
      - api
