services:
  frontend_dev:
    extends:
      file: frontend.config.yml
      service: frontend
    ports:
      - "3000:3000"
    command: ["npm", "run", "_dev"]
  frontend_test:
    extends:
      file: frontend.config.yml
      service: frontend
    ports:
      - "5173:3000"
    command: ["npm", "run", "_serve:test"]
  tests:
    extends:
      file: test.config.yml
      service: tests
    depends_on:
      frontend_test:
        condition: service_healthy
    ports:
      - "3001:3001"
    network_mode: host # Allows container access to public frontend
    environment:
      BASE_URL: "http://localhost:5173" # Public frontend port
