services:
  frontend:
    environment:
      REACT_APP_API_BASE_URL: "http://localhost:4000"
    ports:
      - 3000:3000
    build:
      target: base
    volumes:
      - ../frontend:/app
    command: [npm, start]
  api:
    environment:
      PORT: 80
    ports:
      - 4000:80
    volumes:
      - ../api:/app
    command: ["npm", "run", "dev"]
