services:
  frontend:
    build:
      context: ../frontend/
    depends_on:
      - api
  api:
    build:
      context: ../api/
    command: ["npm", "start"]
    depends_on:
      - database
  database:
    image: postgres:14.1-alpine
