services:
  frontend:
    environment:
      REACT_APP_API_BASE_URL: "http://localhost:4000"
    ports:
      - 3000:3000
    build:
      target: base
    volumes:
      - ../frontend:/app
    command: [npm, start]
  api:
    environment:
      PORT: 80
      DATABASE_URL: postgres://database/
    ports:
      - 4000:80
    volumes:
      - ../api:/app
    command: ["npm", "run", "dev"]
    depends_on:
      - database
  database:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: "sikaeducation"
    volumes:
      - ./database:/var/lib/postgresql/data
