services:
  frontend:
    environment:
      REACT_APP_API_BASE_URL: "http://localhost:4000"
      REACT_APP_AUTH_ZERO_DOMAIN: "dev-6vs4dnoj.us.auth0.com"
      REACT_APP_CLIENT_ID: "xtd3nBAGVaVGHnhH7047XC87o1nMS3dX"
    ports:
      - 3000:3000
    build:
      target: base
    volumes:
      - ../frontend:/app
    command: [npm, start]
  api:
    environment:
      PORT: 80
      DATABASE_URL: postgres://database/
      CLIENT_ORIGIN: http://localhost:3000
    ports:
      - 4000:80
    volumes:
      - ../api:/app
    command: ["npm", "run", "dev"]
  database:
    volumes:
      - ../database:/var/lib/postgresql/data
