services:
  frontend:
    environment:
      REACT_APP_API_BASE_URL: "http://localhost:4000"
      REACT_APP_API_AUTH_URI: "https://api.sikaeducation.com"
      REACT_APP_AUTH_ZERO_DOMAIN: "dev-6vs4dnoj.us.auth0.com"
      REACT_APP_CLIENT_ID: "xtd3nBAGVaVGHnhH7047XC87o1nMS3dX"
      REACT_APP_ACTIVITY_SERVICE_BASE_URL: "https://divine-snow-6176.fly.dev"
      REACT_APP_AUTH_ZERO_AUDIENCE: "https://dev-6vs4dnoj.us.auth0.com/api/v2/"
    ports:
      - 3000:3000
    build:
      target: base
    volumes:
      - ..:/app
    command: [npm, start]
