services:
# services:
#   frontend:
#     environment:
#       REACT_APP_API_BASE_URL: "http://api:80"
#       REACT_APP_AUTH_ZERO_DOMAIN: "dev-6vs4dnoj.us.auth0.com"
#       REACT_APP_CLIENT_ID: "xtd3nBAGVaVGHnhH7047XC87o1nMS3dX"
#     ports:
#       - 3000:3000
#     build:
#       target: base
#   api:
#     environment:
#       PORT: 80
#       DATABASE_URL: postgres://database/
#     expose:
#       - 80
#     build:
#       target: base
#   database:
#     volumes:
#       - ../database:/var/lib/postgresql/data
  tests:
    image: mcr.microsoft.com/playwright:v1.18.0-focal
    # build:
    #   context: ../tests/
    working_dir: "/app"
    environment:
      BASE_URL: "http://frontend:3000"
    depends_on:
      - frontend
      - api
  frontend:
    environment:
      REACT_APP_API_BASE_URL: "http://localhost:4000"
      REACT_APP_AUTH_ZERO_DOMAIN: "dev-6vs4dnoj.us.auth0.com"
      REACT_APP_CLIENT_ID: "xtd3nBAGVaVGHnhH7047XC87o1nMS3dX"
    ports:
      - 3000:3000
    build:
      target: base
    volumes:
      - ../frontend:/app
    command: [npm, start]
  api:
    environment:
      PORT: 80
      DATABASE_URL: postgres://database/
    ports:
      - 4000:80
    volumes:
      - ../api:/app
    command: ["npm", "run", "dev"]
  database:
    volumes:
      - ../database:/var/lib/postgresql/data
