services:
  tests:
    depends_on:
      frontend_test:
        condition: service_healthy
    image: mcr.microsoft.com/playwright:v1.39.0-jammy
    ipc: host # Keeps chrome from OOMing
    working_dir: /app # Default working dir is /
    volumes:
      - ..:/app
