#!/bin/bash
echo "Building containers..."
PARENT_PATH=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd $PARENT_PATH/..

docker-compose -f .docker/docker-compose.yml build
docker build --quiet ./Dockerfile.storybook
