#!/bin/bash
echo "Running Docker Compose with this configuration:"
PARENT_PATH=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd $PARENT_PATH/..
docker-compose -f .docker/docker-compose.yml -f .docker/docker-compose.dev.yml config
docker-compose -f .docker/docker-compose.yml up --abort-on-container-exit
