name: Deploy
on:
  push:
    tags: [v*]
env:
  FORCE_COLOR: 1
jobs:
  test:
    name: Run unit and feature tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: ./scripts/test
  build:
    name: Build app
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
        env:
          REACT_APP_AUTH_ZERO_AUDIENCE: ${{ secrets.AUTH_ZERO_AUDIENCE }}
          REACT_APP_AUTH_ZERO_DOMAIN: ${{ secrets.AUTH_ZERO_DOMAIN }}
          REACT_APP_CLIENT_ID: ${{ secrets.AUTH_ZERO_CLIENT_ID }}
          REACT_APP_ACTIVITY_SERVICE_BASE_URL: ${{ secrets.ACTIVITY_SERVICE_BASE_URL }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: Deploy v${{ github.ref }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: build
          build_command: echo "Build exists, skipping npm run build"
          install_command: echo "Install exists, skipping npm install"
